import type { Product } from '../models/Product';
import type { BuyerRequest } from '../models/Request';
import type { Bid } from '../models/Bid';

export const MOCK_PRODUCTS: Product[] = [];

export const MOCK_REQUESTS: BuyerRequest[] = [
  {
    id: 'r1',
    buyerId: 'b1',
    buyerName: 'John Phiri',
    title: 'Looking for iPhone 13 or 14',
    description: 'Need a good condition iPhone 13 or 14 for my wife\'s birthday. Prefer 128GB in any colour. Must come with original charger.',
    budget: 500000,
    category: 'phones',
    location: 'Lilongwe',
    status: 'open',
    createdAt: Date.now() - 3600000,
    bidCount: 3,
    images: ['https://images.unsplash.com/photo-1632661674596-df8be070a5c5?q=80&w=400'],
  },
  {
    id: 'r2',
    buyerId: 'b2',
    buyerName: 'Mercy Banda',
    title: 'Toyota Fielder 2018-2020 wanted',
    description: 'Looking for a clean Toyota Fielder, 2018 or newer. Automatic, fully-loaded preferred. Budget is negotiable for the right car.',
    budget: 5000000,
    category: 'cars',
    location: 'Blantyre',
    status: 'open',
    createdAt: Date.now() - 7200000,
    bidCount: 5,
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=400'],
  },
  {
    id: 'r3',
    buyerId: 'b3',
    buyerName: 'Chikondi Zulu',
    title: 'Samsung or LG 55" 4K Smart TV',
    description: 'Need a 55-inch 4K Smart TV for our office waiting area. Samsung or LG preferred. Must support Netflix and YouTube.',
    budget: 750000,
    category: 'electronics',
    location: 'Mzuzu',
    status: 'open',
    createdAt: Date.now() - 10800000,
    bidCount: 2,
    images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?q=80&w=400'],
  },
  {
    id: 'r4',
    buyerId: 'b4',
    buyerName: 'Tiyamike Mvula',
    title: 'Maize farming equipment set',
    description: 'Looking for a complete small-scale maize farming tool set. Hoes, rakes, and sprayer. Willing to buy all at once.',
    budget: 180000,
    category: 'farming',
    location: 'Zomba',
    status: 'open',
    createdAt: Date.now() - 18000000,
    bidCount: 1,
    images: ['https://images.unsplash.com/photo-1500937386664-56d1dfef3854?q=80&w=400'],
  },
  {
    id: 'r5',
    buyerId: 'b5',
    buyerName: 'Grace Mwale',
    title: 'Ladies office shoes size 7',
    description: 'Need 2-3 pairs of professional ladies shoes, size 7. Heels between 2-3 inches. Dark colours preferred (black, navy).',
    budget: 60000,
    category: 'fashion',
    location: 'Lilongwe',
    status: 'open',
    createdAt: Date.now() - 21600000,
    bidCount: 4,
  },
];

export const MOCK_BIDS: Bid[] = [
  {
    id: 'bid1',
    requestId: 'r1',
    requestTitle: 'Looking for iPhone 13 or 14',
    sellerId: 'seller1',
    sellerName: 'TechShop Malawi',
    sellerRating: 4.8,
    price: 480000,
    description: 'I have a brand new iPhone 13 128GB in black. Never used, still sealed in box with all accessories. Warranty intact.',
    status: 'pending',
    createdAt: Date.now() - 1800000,
  },
  {
    id: 'bid2',
    requestId: 'r1',
    requestTitle: 'Looking for iPhone 13 or 14',
    sellerId: 'seller2',
    sellerName: 'Peter Kamanga',
    sellerRating: 4.5,
    price: 460000,
    description: 'I have a used iPhone 13 in excellent condition, 128GB, charged less than 300 cycles. Comes with original box.',
    status: 'pending',
    createdAt: Date.now() - 3600000,
  },
  {
    id: 'bid3',
    requestId: 'r1',
    requestTitle: 'Looking for iPhone 13 or 14',
    sellerId: 'seller3',
    sellerName: 'Mobile World',
    sellerRating: 4.2,
    price: 495000,
    description: 'iPhone 14 128GB, rose gold. Bought abroad, unlocked. Perfect condition, 6 months old.',
    status: 'pending',
    createdAt: Date.now() - 7200000,
  },
];

// Seller's own bids (what the logged-in seller has bid on)
export const MY_BIDS: Bid[] = [
  {
    id: 'mybid1',
    requestId: 'r2',
    requestTitle: 'Toyota Fielder 2018-2020 wanted',
    sellerId: 'me',
    sellerName: 'My Shop',
    sellerRating: 4.7,
    price: 4800000,
    description: 'I have a 2019 Toyota Fielder, silver, automatic, fully loaded. Low mileage, accident-free. Can provide all documents.',
    status: 'pending',
    createdAt: Date.now() - 5400000,
  },
  {
    id: 'mybid2',
    requestId: 'r3',
    requestTitle: 'Samsung or LG 55" 4K Smart TV',
    sellerId: 'me',
    sellerName: 'My Shop',
    sellerRating: 4.7,
    price: 720000,
    description: 'Samsung 55" QLED 4K Smart TV. Brand new, still in box. Free delivery within Mzuzu.',
    status: 'accepted',
    createdAt: Date.now() - 86400000,
  },
];
