import type { Product } from '../models/Product';
import type { BuyerRequest } from '../models/Request';
import type { Bid } from '../models/Bid';
import type { SellerProfile } from '../models/Seller';

export const MOCK_PRODUCTS: Product[] = [];

export const MOCK_REQUESTS: BuyerRequest[] = [
  {
    id: 'r1',
    buyerId: 'b1',
    buyerName: 'John Phiri',
    title: 'Looking for iPhone 13 or 14',
    description: 'Need a good condition iPhone 13 or 14 for my wife\'s birthday. Prefer 128GB in any colour. Must come with original charger.',
    budget: 500000,
    category: 'phones',
    location: 'Lilongwe',
    status: 'open',
    createdAt: Date.now() - 3600000,
    bidCount: 3,
    images: ['https://images.unsplash.com/photo-1632661674596-df8be070a5c5?q=80&w=400'],
  },
  {
    id: 'r2',
    buyerId: 'b2',
    buyerName: 'Mercy Banda',
    title: 'Toyota Fielder 2018-2020 wanted',
    description: 'Looking for a clean Toyota Fielder, 2018 or newer. Automatic, fully-loaded preferred. Budget is negotiable for the right car.',
    budget: 5000000,
    category: 'cars',
    location: 'Blantyre',
    status: 'open',
    createdAt: Date.now() - 7200000,
    bidCount: 5,
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=400'],
  },
  {
    id: 'r3',
    buyerId: 'b3',
    buyerName: 'Chikondi Zulu',
    title: 'Samsung or LG 55" 4K Smart TV',
    description: 'Need a 55-inch 4K Smart TV for our office waiting area. Samsung or LG preferred. Must support Netflix and YouTube.',
    budget: 750000,
    category: 'electronics',
    location: 'Mzuzu',
    status: 'open',
    createdAt: Date.now() - 10800000,
    bidCount: 2,
    images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?q=80&w=400'],
  },
  {
    id: 'r4',
    buyerId: 'b4',
    buyerName: 'Tiyamike Mvula',
    title: 'Maize farming equipment set',
    description: 'Looking for a complete small-scale maize farming tool set. Hoes, rakes, and sprayer. Willing to buy all at once.',
    budget: 180000,
    category: 'farming',
    location: 'Zomba',
    status: 'open',
    createdAt: Date.now() - 18000000,
    bidCount: 1,
    images: ['https://images.unsplash.com/photo-1500937386664-56d1dfef3854?q=80&w=400'],
  },
  {
    id: 'r5',
    buyerId: 'b5',
    buyerName: 'Grace Mwale',
    title: 'Ladies office shoes size 7',
    description: 'Need 2-3 pairs of professional ladies shoes, size 7. Heels between 2-3 inches. Dark colours preferred (black, navy).',
    budget: 60000,
    category: 'fashion',
    location: 'Lilongwe',
    status: 'open',
    createdAt: Date.now() - 21600000,
    bidCount: 4,
  },
];

export const MOCK_BIDS: Bid[] = [
  {
    id: 'bid1',
    requestId: 'r1',
    requestTitle: 'Looking for iPhone 13 or 14',
    sellerId: 'seller1',
    sellerName: 'TechShop Malawi',
    sellerRating: 4.8,
    price: 480000,
    description: 'I have a brand new iPhone 13 128GB in black. Never used, still sealed in box with all accessories. Warranty intact.',
    status: 'pending',
    createdAt: Date.now() - 1800000,
  },
  {
    id: 'bid2',
    requestId: 'r1',
    requestTitle: 'Looking for iPhone 13 or 14',
    sellerId: 'seller2',
    sellerName: 'Peter Kamanga',
    sellerRating: 4.5,
    price: 460000,
    description: 'I have a used iPhone 13 in excellent condition, 128GB, charged less than 300 cycles. Comes with original box.',
    status: 'pending',
    createdAt: Date.now() - 3600000,
  },
  {
    id: 'bid3',
    requestId: 'r1',
    requestTitle: 'Looking for iPhone 13 or 14',
    sellerId: 'seller3',
    sellerName: 'Mobile World',
    sellerRating: 4.2,
    price: 495000,
    description: 'iPhone 14 128GB, rose gold. Bought abroad, unlocked. Perfect condition, 6 months old.',
    status: 'pending',
    createdAt: Date.now() - 7200000,
  },
];

export const MOCK_SELLERS: SellerProfile[] = [
  // Lilongwe — phones & electronics
  {
    id: 'seller1',
    name: 'TechShop Malawi',
    rating: 4.8,
    phone: '+265 888 123 456',
    location: 'Area 3, Lilongwe',
    lat: -13.958,
    lng: 33.780,
    categories: ['phones', 'electronics'],
    totalSales: 142,
    bio: 'Authorised dealer for Samsung and Tecno. Same-day delivery within Lilongwe.',
  },
  {
    id: 'seller2',
    name: 'Peter Kamanga',
    rating: 4.5,
    phone: '+265 999 234 567',
    location: 'Area 47, Lilongwe',
    lat: -13.967,
    lng: 33.769,
    categories: ['phones'],
    totalSales: 58,
    bio: 'Private seller specialising in used iPhones and Android flagships.',
  },
  {
    id: 'seller3',
    name: 'Mobile World',
    rating: 4.2,
    phone: '+265 888 345 678',
    location: 'City Centre, Lilongwe',
    lat: -13.971,
    lng: 33.787,
    categories: ['phones', 'electronics'],
    totalSales: 203,
    bio: 'Wide selection of new and refurbished phones. Warranty on all devices.',
  },
  {
    id: 'seller4',
    name: 'City Electronics',
    rating: 4.6,
    phone: '+265 999 456 789',
    location: 'Area 6, Lilongwe',
    lat: -13.952,
    lng: 33.784,
    categories: ['electronics', 'phones', 'household'],
    totalSales: 87,
    bio: 'TVs, home appliances, and phones at competitive prices.',
  },
  // Blantyre — cars
  {
    id: 'seller5',
    name: 'AutoMart Malawi',
    rating: 4.7,
    phone: '+265 888 567 890',
    location: 'Ginnery Corner, Blantyre',
    lat: -15.782,
    lng: 35.011,
    categories: ['cars'],
    totalSales: 34,
    bio: 'Importing quality Japanese and South African vehicles. All cars cleared and roadworthy.',
  },
  {
    id: 'seller6',
    name: 'TopGear Motors',
    rating: 4.4,
    phone: '+265 999 678 901',
    location: 'Chirimba, Blantyre',
    lat: -15.790,
    lng: 35.001,
    categories: ['cars'],
    totalSales: 21,
    bio: 'Second-hand cars with full service history. Financing options available.',
  },
  {
    id: 'seller7',
    name: 'Drive Easy BT',
    rating: 4.1,
    phone: '+265 888 789 012',
    location: 'Limbe, Blantyre',
    lat: -15.797,
    lng: 35.019,
    categories: ['cars'],
    totalSales: 15,
    bio: 'Affordable family cars and pickups. Trade-ins welcome.',
  },
  // Mzuzu — electronics
  {
    id: 'seller8',
    name: 'Northern TVs',
    rating: 4.3,
    phone: '+265 888 890 123',
    location: 'Mzuzu City Centre',
    lat: -11.462,
    lng: 34.026,
    categories: ['electronics', 'household'],
    totalSales: 67,
    bio: 'Best prices on Smart TVs and home electronics in the north.',
  },
  // Zomba — farming
  {
    id: 'seller9',
    name: 'FarmPro Tools',
    rating: 4.9,
    phone: '+265 999 901 234',
    location: 'Zomba Town',
    lat: -15.379,
    lng: 35.320,
    categories: ['farming'],
    totalSales: 110,
    bio: 'Complete farming equipment supplier. Bulk discounts for cooperatives.',
  },
  {
    id: 'seller10',
    name: 'Agri Supply Co.',
    rating: 4.5,
    phone: '+265 888 012 345',
    location: 'Zomba Market',
    lat: -15.385,
    lng: 35.311,
    categories: ['farming', 'household'],
    totalSales: 78,
    bio: 'Hand tools, sprayers, seeds, and fertiliser bags. Free delivery on large orders.',
  },
  // Lilongwe — fashion
  {
    id: 'seller11',
    name: 'Style Hub',
    rating: 4.6,
    phone: '+265 999 123 456',
    location: 'Old Town, Lilongwe',
    lat: -13.955,
    lng: 33.776,
    categories: ['fashion', 'beauty'],
    totalSales: 194,
    bio: 'Ladies and gents clothing, shoes, and accessories. New stock every week.',
  },
  {
    id: 'seller12',
    name: 'Chic Boutique',
    rating: 4.4,
    phone: '+265 888 234 567',
    location: 'Area 18, Lilongwe',
    lat: -13.963,
    lng: 33.773,
    categories: ['fashion'],
    totalSales: 83,
    bio: 'Office wear and casual wear for women. Custom tailoring available.',
  },
];

// Seller's own bids (what the logged-in seller has bid on)
export const MY_BIDS: Bid[] = [
  {
    id: 'mybid1',
    requestId: 'r2',
    requestTitle: 'Toyota Fielder 2018-2020 wanted',
    sellerId: 'me',
    sellerName: 'My Shop',
    sellerRating: 4.7,
    price: 4800000,
    description: 'I have a 2019 Toyota Fielder, silver, automatic, fully loaded. Low mileage, accident-free. Can provide all documents.',
    status: 'pending',
    createdAt: Date.now() - 5400000,
  },
  {
    id: 'mybid2',
    requestId: 'r3',
    requestTitle: 'Samsung or LG 55" 4K Smart TV',
    sellerId: 'me',
    sellerName: 'My Shop',
    sellerRating: 4.7,
    price: 720000,
    description: 'Samsung 55" QLED 4K Smart TV. Brand new, still in box. Free delivery within Mzuzu.',
    status: 'accepted',
    createdAt: Date.now() - 86400000,
  },
];
